export const languages: { [key: string]: string }[] = Object.entries({
  Afrikaans: "af",
  Amharic: "am",
  Arabic: "ar",
  Basque: "eu",
  Bengali: "bn",
  Bulgarian: "bg",
  Catalan: "ca",
  Cherokee: "chr",
  Croatian: "hr",
  Czech: "cs",
  Danish: "da",
  Dutch: "nl",
  "English (US)": "en",
  "English (UK)": "en-GB",
  Estonian: "et",
  Filipino: "fil",
  Finnish: "fi",
  "French (Canada)": "fr-CA",
  "French (France)": "fr-FR",
  German: "de",
  Greek: "el",
  Gujarati: "gu",
  Hebrew: "iw",
  Hindi: "hi",
  Hungarian: "hu",
  Icelandic: "is",
  Indonesian: "in",
  Italian: "it",
  Japanese: "ja",
  Kannada: "kn",
  Korean: "ko",
  Latvian: "lv",
  Lithuanian: "lt",
  Malay: "ms",
  Malayalam: "ml",
  Marathi: "mr",
  Norwegian: "no",
  Polish: "pl",
  "Portuguese (Brazil)": "pt-BR",
  "Portuguese (Portugal)": "pt-PT",
  Romanian: "ro",
  Russian: "ru",
  Serbian: "sr",
  Slovak: "sk",
  Slovenian: "sl",
  "Spanish (Spain)": "es-ES",
  "Spanish (Latin America)": "es-419",
  Swahili: "sw",
  Swedish: "sv",
  Tamil: "ta",
  Telugu: "te",
  Thai: "th",
  Turkish: "tr",
  Ukrainian: "uk",
  Vietnamese: "vi",
  Welsh: "cy",
  Zulu: "zu",
}).map(([label, value]) => ({ label, value }));
